version: "3.9"

services:
  app:
    container_name: url-shortner
    restart: always
    build: ./url-shortner
    environment:
      PG_PASS_V1: Batsy!1996
    ports: 
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    volumes:
      - ./data:/data/db
      - ./url_shortner_dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Batsy!1996
    expose:
      - 5432
    ports:
      - "5433:5432"
      
  frontend:
    container_name: users_ui
    restart: always
    build: ./client
    ports:
      - "1234:1234"
    links:
      - "app"